run:
	@python3 scrape.py

depend3:
	@pip3 install beautifulsoup4
	@pip3 install pandas
	@pip3 install selenium
	@pip3 install openpyxl

depend:
	@pip install beautifulsoup4
	@pip install pandas
	@pip install selenium
	@pip install openpyxl